SELECT 
  CONCAT(
    'ALTER TABLE garantiaSM.',
    TABLE_NAME,
    ' MODIFY COLUMN ',
    COLUMN_NAME, 
    ' BIGINT UNSIGNED', 
    IF(IS_NULLABLE='NO', ' NOT NULL ', ' '), 
    EXTRA,
    IF(COLUMN_COMMENT='','',CONCAT('COMMENT ',"'",COLUMN_COMMENT,"'")),
    ';'  ) AS deletethis
FROM 
  INFORMATION_SCHEMA.COLUMNS 
WHERE 
  TABLE_SCHEMA='garantiaSM' 
  AND 
  (COLUMN_NAME='ID' OR COLUMN_NAME like '%ID')
  AND DATA_TYPE='int'
  and   TABLE_NAME NOT IN 
   (SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='garantiaSM' ANd TABLE_TYPE='VIEW');